name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  websocketscomponent5:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 1024
    timeout: 20
    ufs: true

components:
  socks:
    type: AwsWebSockets
    inputs:
      provider: ${this.providers.aws}
      apiName: websocketscomponent5
      routeSelectionExpression: $request.body.action
      routes:
        $connect: ${this.functions.websocketscomponent5}
        $disconnect: ${this.functions.websocketscomponent5}
        $default: ${this.functions.websocketscomponent5}
#        message: ${this.functions.websocketscomponent5}
