name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  IdempotentCron10:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 512
    timeout: 20
    ufs: true

components:
  cron:
    type: Cron
    inputs:
      function: ${this.functions.IdempotentCron10}
      rate: 7m
