name: AwsCloudWatchEventsRule
extends: Component
main: ./dist/index.js
version: 0.3.0

enabled: ${inputs.enabled}
lambda: ${inputs.lambda}
provider: ${inputs.provider}
schedule: ${inputs.schedule}

inputTypes:
  enabled:
    type: boolean
  lambda:
    type: object
  provider:
    type: AwsProvider
    required: true
  schedule:
    type: string
